version: '3.8'
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - .data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  back:
    container_name: back
    build:
      context: ./library_back
      network: host
    command: bash -c " python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - ./library_back:/docker/gces
    ports:
      - "8000:8000"
    depends_on:
      - db
  front:
    container_name: front
    build: ./library_front
    volumes:
      - './library_front:/app'
      - '/library_front/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start