version: '3.8'
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - .data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password