name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up --build -d

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Connect to Postgres
        run: docker run --name postgres -e POSTGRES_PASSWORD=password -d -p 5432:5432 postgres

      - name: Run tests
        run: export PGPASSWORD=password; psql -h 0.0.0.0 -U postgres

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./library_back/requirements.txt
          pip install pylint

      - name: Run lint backend
        run: cd library_back/ && pylint ./manage.py